 name:Generate Contribution Snake

"on":
  workflow_dispatch: {}
  schedule:
    - cron: "0 0 * * *"
  push:
    branches: [main]
    paths:
      - ".github/workflows/snake.yml"

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-24.04
    timeout-minutes: 10
    steps:
      - name: Generate contribution snake
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: imsanilka
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark

      - name: Publish contribution snake
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: output
          commit_message: "Update contribution snake"
